### ISSUE TITLE
Error installation of the pluggin on Windows

### ISSUE THREAD

**Issue by MarineChap** [open-ephys-plugins/ZMQInterface#3]
I am having an error when trying to install this pluggin on a window computer. 
The doc said it is compatible with Windows.
![image](https://user-images.githubusercontent.com/34722888/100219100-e18f0f80-2f15-11eb-8dc3-bd2b8f90172e.png)

Do you know what is happening here ? 

Thanks. Have a good day.

**Comment by anjaldoshi** [comment]
Hi Marine,

Looks like ZMQInterface is not able to find its dependency (libzmq) after installation. 

I'll need some information before I can help you figure out the reason behind this. What version of the GUI are you running? Did you build the GUI from source or did you install it using the ZIP / installer? If you installed it, were you running any previous version of the GUI before installing the current version? 

Thanks,
Anjal

**Comment by MarineChap** [comment]
Seems odd as the libzmq-v120-mt-4_0_4.dll is indeed added in the shared folder. 

_What version of the GUI are you running?_  **v0.5.2.2** 

_Did you build the GUI from source or did you install it using the ZIP / installer?_  **ZIP/installer  Install-Open-Ephys-GUI-v0.5.2.2**

_If you installed it, were you running any previous version of the GUI before installing the current version?_ Y**es the version before was v0.5.2.1 but we remove the OpenEphys folder before reinstalling. That's not enough to have a clean install ?**

**Comment by anjaldoshi** [comment]
Thanks for all the info, Marine!

> Seems odd as the libzmq-v120-mt-4_0_4.dll is indeed added in the shared folder.

Are you talking about the shared folder present inside the Open Ephys installation folder (next to open-ephys.exe)?

Can you check whether `libzmq-v120-mt-4_0_4.dll` is also present inside `C:\ProgramData\Open Ephys\shared`. If it is not, can you copy it over there too? It should have been copied over to that directory by the installer, but it looks like it didn't happen in your case. This is required because plugins installed via Plugin Installer are saved in `C:\ProgramData\Open Ephys\plugins` directory and so it needs the dependencies in `C:\ProgramData\Open Ephys\shared`
Also, ProgramData directory is a hidden directory, so you'll have to turn on "Show hidden files, folders, and drives" by following [these steps](https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-10-97fbc472-c603-9d90-91d0-1166d1d9f4b5).

**Comment by MarineChap** [comment]
No I was saying it is indeed in `C:\ProgramData\Open Ephys\shared`
![image](https://user-images.githubusercontent.com/34722888/100269292-9812e480-2f56-11eb-872b-1b462e9d7648.png)

**Comment by anjaldoshi** [comment]
I just installed ZMQInterface via Plugin Installer on my Windows machine, and it installed and loaded perfectly fine. 
![image1](https://user-images.githubusercontent.com/11559287/100271183-ed76d380-2f0d-11eb-8a3a-04cf7b155783.png)
![image](https://user-images.githubusercontent.com/11559287/100271189-eea80080-2f0d-11eb-9a71-33078100bf71.png)

Does it show the same error (DLL Error 0x7e) in the debug console while loading ZMQInterface when you re-run the GUI?

**Comment by MarineChap** [comment]
Oh la la what is this bug! I have exactly the same files as yours. 
And yes it re-show the same error when re-launching. 

Just to be sure, to fully uninstall OpenEphys I just have to remove the folder in ProgramData and ProgramFiles ? Not another folder somewhere else ? 
I want to be sure to have a clean installation.

**Comment by anjaldoshi** [comment]
Yeah, that should be it. But, I would suggest for clean installation, go to Control Panel->Programs & Features and then uninstall Open Ephys GUI from there, then remove the Open Ephys folder from ProgramData. After that, install Open Ephys GUI again using the latest installer.

![image (1)](https://user-images.githubusercontent.com/11559287/100272827-a3432180-2f10-11eb-8431-0c001046dda0.png)

Can you try this and then try installing ZMQInterface again? If that still doesn't work, can you try and install other plugins like NetworkEvents or PhaseCalculator and see if they work?

**Comment by MarineChap** [comment]
So I did that. Still all the extensions with zmqlib  are not working - no problem with the others (PhaseCalculators...ect.)

**Comment by anjaldoshi** [comment]
So, definitely something is wrong with libzmq in your installation. How about **moving** the ZMQInterface.dll from `ProgramData\Open Ephys\plugins` to `Program Files\Open Ephys\plugins` (or wherever you installed Open Ephys) and `libzmq-v120-mt-4_0_4.dll` from `ProgramData\Open Ephys\shared` to `Program Files\Open Ephys\shared`. Does that work?

**Comment by MarineChap** [comment]
Nope that does not work. Is it normal that the zmqdll lib was already in both shared folder at the normal installation of OpenEphys (without the plugin) ?

**Comment by MarineChap** [comment]
Sorry, you lost enough time with my own computer problem as apparently this computer is the only one on earth bugging like this. I will probably make it work at some point for obscure reason. 
Thank you for your help :)
